env:
  browser: true
  es6: true
extends: 'eslint:recommended'
rules:
  no-console:
    - off
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  # quotes:
  #   - error
  #   - single
  semi:
    - error
    - always
